# Read the documentation: https://fosrestbundle.readthedocs.io/en/3.x/
fos_rest:
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
    routing_loader: false
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
    format_listener:
        rules:
            - { path: ^/, priorities: [ html, json ], fallback_format: ~, prefer_extension: true}
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
